apiVersion: config.openshift.io/v1
kind: OAuth
metadata:
  name: cluster
spec:
  identityProviders:
  # Preserve OpenShift Local HT-Passwd Developer
  - htpasswd:
      fileData:
        name: htpass-secret
    mappingMethod: claim
    name: developer
    type: HTPasswd
  # Keycloak GitOps Admin IdP
  - name: keycloak
    mappingMethod: claim
    type: OpenID
    openID:
      ca:
        name: keycloak-oidc-ca
      clientID: openshift
      clientSecret:
        name: keycloak-oidc-secret
      issuer: https://keycloak-keycloak.apps-crc.testing/realms/openshift
      claims:
        preferredUsername:
        - preferred_username
        name:
        - name
        email:
        - email
