apiVersion: k8s.keycloak.org/v2alpha1
kind: KeycloakRealmImport
metadata:
  name: openshift-realm
  namespace: keycloak
spec:
  keycloakCRName: keycloak
  realm:
    id: openshift
    realm: openshift
    enabled: true
    users:
      - username: testuser
        enabled: true
        credentials:
          - type: password
            value: "password"
        realmRoles:
          - default-roles-openshift
    clients:
      - clientId: openshift
        secret: mysecret123
        enabled: true
        protocol: openid-connect
        standardFlowEnabled: true
        implicitFlowEnabled: false
        directAccessGrantsEnabled: true
        redirectUris:
          - "https://oauth-openshift.apps-crc.testing/*"
