---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: custom-keycloak-admin-secret
  namespace: keycloak
spec:
  encryptedData:
    password: AgANdspW7ZJ3mDzJ0OtMo5MpyzK5iniTpHEbLtB+rHhhKkwNCrnhSpEb3HjdAh5XWu81FHtPQNXalMbX3er3dN//xtdEhLd1K59rd3ytR5bJ3dBUuGK7s7qDRmpJbxejZmKrMM3nGjintVk5ReUA8EISKKJKc3OwSXRk96kM47+rVq6IhI83FsYVqFeRrta2PylEB8rdNkQ9zcnnzv2nMGmUVsSoyuhDPB95RtwonwszPQHhQl5TD8vhlsQ889phwkF8DBFB4aK+Mx+KkNdkITnyOUgagqm8tIc8FnfulTLjqnYke7Ijj6KEZAsO+CtAwTayKe6sr7lr/hPiN6dXT5Jj0IIjkg4Hewakz8p5sBAM4gVB8ucBgunmB3pwLk2bGQmUgB33XTHhv7HMgdRmRt/7iHdvbvu1dYx2DBMPnRFrTJDc5XaoQ7Xi2MyIzOmdbYNc74L0SxTZy+XsUzWJV+HXtl+9V9gqTcBDYG32oQXEUgZD3Bqssn5IFG2D9IBLyuPwGhBlke1I3SYO66kgBbc+sKMfpwhESQsSlLFlOVfI9wCMAqLxQaxrntPjF/Dxfk43rhrDlFRd8l9Y1ak+PgdAoqn6R5c5quw6PtGxYjanRIOqw4S+C39bhzu73h8UwSvyoB/WxmWIrd1zpYW22Uv2IkVqCpA4V7N9WFYm+yRGAXL6vqupwpOKjn3OzD3KdRrJXx2RwNvnobLx
    username: AgA62zrpCNPlHrdAtLjWwlY5eZnEMn4k8YA2cEW1Mgv2EMMWIxIo89KjNG5wnk8+uRC0qQXlgI3Mdp2x2yn6xOH281i+lWtKsGamDPNjauj6xbT46peKe/P7vGwXASRqNnJYDPquMFf9+U7oTuyAJt/dpq92PmkyHfrHHpPbHb6wUo60H1JNpTQtc9lm8kehuYqNM4wIwwbLUI/zid/+tMp68QUQckNF2WcB5/wk2i/7NKn82HPYyThIwPKT08aOSwiCrl4fyh2GIQhz3ihKC0rfZ/EGwOZaTY8HUnuyNJ+3QK0zGQrFltAPh3zdOgERnNuTPanWylFbqac7g2yuTB2ymHM9R6kt+S0+OozDgRuNts2EC3uBKijlO3xY8NWHBeF1mmsU9GzRpIVyvJoEbaV7DQHewakJeU4NSNtr4Qu98Xs57tvthYizz04uYKcjemVk8qrU572jdNCXB1/++A0kWEnO+PKxFKNI3Z5k/t/w9AF7TtGiLdrKs3JRmQV3SCIbHrDS36hdaCbPgdAxUPK5pn29fplL3vyD474FaUC9meP2N7fmJJV+GDyQf9kSkFSfm63usbnwpO64I0J2KfyW6sOPbRzVke5h6bO3voUtVRDzZ04bzHPstRiDUA3TxzxG9NOz5KJjkpJMrbsfQHP7SlpOPQaqYXGkaYfGeP2tpqclbfGfzMOna6ey8Hj8EWasgj2swmNw
  template:
    metadata:
      name: custom-keycloak-admin-secret
      namespace: keycloak
    type: Opaque
