---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: keycloak-realm-secrets
  namespace: keycloak
spec:
  encryptedData:
    REALM_OIDC_CLIENT_SECRET: AgATe3S8nO3rwPOsdL4MGVtbW4Xnc6zCYLzJPbV2zlYr834lq7cAKcfrQvvM4ISSM1reg2yspsdFCvXrEHBfSxmwaCpsT9xRNQsj3u1k2C4+nQ7V38YCO/H5yTrUeBg0zAdX+b8h+Qs8nuDr96zkYRX6om/o6ngYlg8mJChMSkhjQ9XSu+GG6lFsudIm5ulsawoQlcAl2dioGmbjxABtyMvBjjvFl4eF8CfDaqq+58jj5lGLAcWFmpOUv3Mz62urrnK/gmO+KoIdU0g8K6QyQj3QXchPNhO8zRsUD5mLoP+NqjH0+XRIpoOkGwJzndeoXgAZe+n5unnrFMrPKvjMMWpGuIuKDCH1ZlPSxzP/GZzNyw6sRxjO5UhqrR4D4nGph7eTEvRhcMiprPGqCgLXwvddtjbYwZdEHQCcwmiFIir1FbpGFpSuz+RtmHuL7dFCsGEB8/79ywcsoQPNPX+BuTgCnPjf7jnA236vvyPZl1UXr36Qt8z1RLCZfxelXcsEB1eUQCvIXcMOhyunpTmMyvkcwpFrnYKhFQCz2lpOlQZEJM5Rxx8Wa+i8+Aaqe/8EaBnWfHtOxA8SrYyYTFyiBKYXq3O2733f7btNTisKqxXXeTiAfMR+nH45szhIJqm5un1FWpcWv2UXEYeFPJTA4gpCy9iJK0e4FCYnIAbNP7jRt28BIg0px4trSqc1F3tDWlgIw7f5pseisRyWDpDq1YABmbf/4uEcbIizZOQSyURFAg==
    REALM_USER_PASSWORD: AgAMfQTk1q7MbJFNW5FVUbcBI4DKL9MIdxr0lXq04lHeADqKhFaM0NA/BTZ7Flpoga3AK4h0RNgGnV0n6eiqd4Nz3BcdDgzyuzib6vnWHq1qEeyDYNTf0LEGHl7/Cx2RNbOvAr24YjbIjVBDmMCDMbluPjvnowN+SI4jnGRAE3dm6h7M8mO87LpoGKFNiFsBvRIm46kWTy3IkB42Qm9qRBEb46kVbMHslkLINRTW5I18waiDhWL4RHMHYi151TIOEO11lHT++ePcbWsyITJCWaPHXjQRui8MGtB+39+I3vyUduYLxZpGqxg3UaH8JAhLVAQrsIemFCijZRyzd8Dqj34aRQqm6+IW2Q50LGiSxh3G+rvCaKwyLf0slFfyZcw8oq4NC0bzbwF0reQY/gQiDpPsRwuVYiSUXgpoivW+wMqupAr+AT2kyMN/93gbgYK3eNZh5BDskz5ZjrAAjwaLAEUZ8QPm1/oWknnv+48ZbV+jmL+o8eMDAZPAyNP9czPEw69pAEp6qUi+6ix1blBSBUcfWEZF2PjBPPfCiL7FxCvlPctDPw9U85CAgjQETf+QH154l9Ce2TdYyQnfX3qsS6uk5YIx6hWP0dN70If5Bl+bqIy/JCBskT330j/8DQJJasklm1gHQ01mdZg190rH+znMViaRE7gxjfHt9pSB/11f4EF96arqnP6V6ftv4a6pHqNONwScpLDH7NH4
  template:
    metadata:
      name: keycloak-realm-secrets
      namespace: keycloak
    type: Opaque
